### ISSUE TITLE
.

### ISSUE THREAD

**Issue by MusaAqeel** [nehab2mail/portfolio#1]

**Comment by nehab2mail** [comment]
Thank You :)

**Comment by nehab2mail** [comment]
Thank You :)
I have applied for York University's Work-Integrated Learning (WIL) program for the upcoming Fall 2024 semester. I have noticed that you are a distinguished alumnus from the previous year, I would like to inquire about your experiences and ask a few questions regarding this program.

**Comment by MusaAqeel** [comment]
my phone number is on my resume just text me there i guess.

**Comment by MusaAqeel** [comment]
also, delete this issue after lol
